2024-04-19 19:03:46,252 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getMe "HTTP/1.1 200 OK"
2024-04-19 19:03:46,321 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/deleteWebhook "HTTP/1.1 200 OK"
2024-04-19 19:03:46,321 - telegram.ext.Application - INFO - Application started
2024-04-19 19:03:56,592 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:04:03,221 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:04:03,586 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:04:07,918 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:04:08,118 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:04:10,407 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:04:10,636 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:04:11,587 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:04:11,776 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:04:13,539 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:04:13,756 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:04:15,593 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:04:15,815 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:04:18,570 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:04:18,571 - root - INFO - 
********
NO GEONAMES USERNAME SET!
Using the default geonames username is not recommended, please set a custom one!
You can get one for free here:
https://www.geonames.org/login
Keep in mind that the default username is limited to 2000 requests per hour and is shared with everyone else using this library.
********
2024-04-19 19:04:18,571 - root - WARNING - No nation specified, using GB as default
2024-04-19 19:04:18,571 - root - WARNING - No latitude specified, using London as default
2024-04-19 19:04:18,571 - root - WARNING - No longitude specified, using London as default
2024-04-19 19:04:18,571 - root - INFO - Fetching timezone/coordinates from geonames
2024-04-19 19:04:18,962 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:04:19,157 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:04:29,603 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 1419, in getresponse
    response.begin()
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 1419, in getresponse
    response.begin()
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Om\miniconda3\Lib\site-packages\telegram\ext\_application.py", line 1277, in process_update
    await coroutine
  File "C:\Users\Om\miniconda3\Lib\site-packages\telegram\ext\_handlers\conversationhandler.py", line 857, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Om\Projects\AstroBot\run_telegram.py", line 154, in location
    prediction = get_astrological_prediction(context.user_data["name"], context.user_data["location"], chart)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Om\Projects\AstroBot\run_telegram.py", line 72, in get_astrological_prediction
    response = requests.post(endpoint, headers=headers, json=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-04-19 19:04:29,611 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:04:39,660 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:04:49,762 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:04:59,837 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:05:02,922 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getMe "HTTP/1.1 200 OK"
2024-04-19 19:05:02,995 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/deleteWebhook "HTTP/1.1 200 OK"
2024-04-19 19:05:02,996 - telegram.ext.Application - INFO - Application started
2024-04-19 19:05:05,867 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:05:06,147 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:05:08,483 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:05:08,672 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:05:15,213 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:05:15,598 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:05:16,712 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:05:16,992 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:05:18,085 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:05:18,368 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:05:21,479 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:05:21,702 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:05:23,796 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:05:23,796 - root - INFO - 
********
NO GEONAMES USERNAME SET!
Using the default geonames username is not recommended, please set a custom one!
You can get one for free here:
https://www.geonames.org/login
Keep in mind that the default username is limited to 2000 requests per hour and is shared with everyone else using this library.
********
2024-04-19 19:05:23,797 - root - WARNING - No nation specified, using GB as default
2024-04-19 19:05:23,797 - root - WARNING - No latitude specified, using London as default
2024-04-19 19:05:23,797 - root - WARNING - No longitude specified, using London as default
2024-04-19 19:05:23,797 - root - INFO - Fetching timezone/coordinates from geonames
2024-04-19 19:05:24,175 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:05:24,369 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:05:35,705 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 1419, in getresponse
    response.begin()
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 1419, in getresponse
    response.begin()
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Om\miniconda3\Lib\site-packages\telegram\ext\_application.py", line 1277, in process_update
    await coroutine
  File "C:\Users\Om\miniconda3\Lib\site-packages\telegram\ext\_handlers\conversationhandler.py", line 857, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Om\Projects\AstroBot\run_telegram.py", line 154, in location
    prediction = get_astrological_prediction(context.user_data["name"], context.user_data["location"], chart)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Om\Projects\AstroBot\run_telegram.py", line 72, in get_astrological_prediction
    response = requests.post(endpoint, headers=headers, json=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-04-19 19:05:35,709 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:05:45,806 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:05:55,901 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:06:05,975 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:06:16,062 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:06:26,149 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:06:36,218 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:06:45,550 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:06:45,551 - root - INFO - 
********
NO GEONAMES USERNAME SET!
Using the default geonames username is not recommended, please set a custom one!
You can get one for free here:
https://www.geonames.org/login
Keep in mind that the default username is limited to 2000 requests per hour and is shared with everyone else using this library.
********
2024-04-19 19:06:45,551 - root - WARNING - No nation specified, using GB as default
2024-04-19 19:06:45,551 - root - WARNING - No latitude specified, using London as default
2024-04-19 19:06:45,551 - root - WARNING - No longitude specified, using London as default
2024-04-19 19:06:45,551 - root - INFO - Fetching timezone/coordinates from geonames
2024-04-19 19:06:46,371 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:06:46,554 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:06:56,966 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 1419, in getresponse
    response.begin()
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 1419, in getresponse
    response.begin()
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Om\miniconda3\Lib\site-packages\telegram\ext\_application.py", line 1277, in process_update
    await coroutine
  File "C:\Users\Om\miniconda3\Lib\site-packages\telegram\ext\_handlers\conversationhandler.py", line 857, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Om\Projects\AstroBot\run_telegram.py", line 154, in location
    prediction = get_astrological_prediction(context.user_data["name"], context.user_data["location"], chart)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Om\Projects\AstroBot\run_telegram.py", line 72, in get_astrological_prediction
    response = requests.post(endpoint, headers=headers, json=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Om\miniconda3\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-04-19 19:06:56,974 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:07:40,702 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getMe "HTTP/1.1 200 OK"
2024-04-19 19:07:40,766 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/deleteWebhook "HTTP/1.1 200 OK"
2024-04-19 19:07:40,766 - telegram.ext.Application - INFO - Application started
2024-04-19 19:07:48,599 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:07:49,043 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:07:50,945 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:07:51,147 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:07:53,626 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:07:53,843 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:07:55,525 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:07:55,711 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:07:58,389 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:07:58,580 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:08:00,609 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:08:00,794 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:08:03,434 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:08:03,435 - root - INFO - 
********
NO GEONAMES USERNAME SET!
Using the default geonames username is not recommended, please set a custom one!
You can get one for free here:
https://www.geonames.org/login
Keep in mind that the default username is limited to 2000 requests per hour and is shared with everyone else using this library.
********
2024-04-19 19:08:03,435 - root - WARNING - No nation specified, using GB as default
2024-04-19 19:08:03,435 - root - WARNING - No latitude specified, using London as default
2024-04-19 19:08:03,435 - root - WARNING - No longitude specified, using London as default
2024-04-19 19:08:03,435 - root - INFO - Fetching timezone/coordinates from geonames
2024-04-19 19:08:03,822 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:08:04,055 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:08:13,612 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:08:13,653 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:08:15,893 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:08:23,255 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:08:23,673 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:08:30,646 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:08:33,760 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:08:38,045 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:08:43,823 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:08:45,391 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:08:52,824 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:08:53,906 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:09:04,037 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:09:10,145 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/sendMessage "HTTP/1.1 200 OK"
2024-04-19 19:09:14,143 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:09:24,247 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:09:34,307 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:09:44,420 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:09:54,514 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:10:04,572 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:10:14,683 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:10:24,762 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:10:34,824 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:10:44,920 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
2024-04-19 19:10:55,045 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7005636792:AAFsRSBKvxA67FoQao1f7AdjPxYKvwk9cvY/getUpdates "HTTP/1.1 200 OK"
